let name = 'Oleksandr';
let lastname = 'Logvyn';

let userName = prompt('Please provide your name:');
alert('Привіт, ' + userName);

console.log(userName);

let userAge = prompt('Please provide date of birth:yyyy.mm');
alert('2022.06' - userAge);

console.log(userAge);

let square_perimeter = prompt('Please provide size of one side of the square to count perimeter');
alert(square_perimeter * 4);

console.log(square_perimeter);


/*let 1example = 'Oleksandr';
 let !example2 = 'Logvyn'; */
//let example-3 = 'Oleksandr';
